# Generated by Django 4.1 on 2023-03-26 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Book Title')),
                ('copies', models.IntegerField(default=1)),
                ('shelved_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('shelved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_shelved_by', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject+', to='subjects.subject')),
            ],
        ),
    ]
