# Generated by Django 4.1 on 2023-03-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('A', 'Librarian 1'), ('B', 'Librarian 2'), ('C', 'Librarian 3'), ('D', 'Chief Librarian')], max_length=2),
        ),
    ]
