name: DjangoBoko Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  DOCKER_REPO: ${{secrets.DOCKER_REPO}}
  DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASS: ${{secrets.DOCKER_PASSWORD}}
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - run: $DOCKER_REPO an $DOCKER_USER 
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.0
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Run Tests
      run: |
        python backend/manage.py test
    - name: Build the Docker image
      run: docker build -t $DOCKER_REPO:$(date +%s) ./backend
